parameters:

    # Contract
    narmafzam_archive_entity_contract: Narmafzam\ArchiveBundle\Entity\Contract
    narmafzam_archive_form_back_contract: Narmafzam\ArchiveBundle\Form\Back\ContractType
    narmafzam_archive_form_front_contract: Narmafzam\ArchiveBundle\Form\Front\ContractType

    # ContractAttachment
    narmafzam_archive_entity_contract_attachment: Narmafzam\ArchiveBundle\Entity\ContractAttachment

services:

    # Contract
    Narmafzam\ArchiveBundle\Model\Handler\ContractHandler:
        arguments:
            - '@doctrine.orm.entity_manager'
            - %upload_directory%

    Narmafzam\ArchiveBundle\Form\Common\ContractType:
        arguments:
            $dataClass: %narmafzam_archive_entity_contract%
        tags:
            - {name: form.type}

    Narmafzam\ArchiveBundle\Controller\Back\ContractController:
        arguments:
            $dataClass: %narmafzam_archive_entity_contract%
            $formTypeClass: %narmafzam_archive_form_back_contract%
            $handler: '@Narmafzam\ArchiveBundle\Model\Handler\ContractHandler'
        tags:
            - name: 'controller.service_arguments'

    Narmafzam\ArchiveBundle\Controller\Front\ContractController:
        arguments:
            $dataClass: %narmafzam_archive_entity_contract%
            $formTypeClass: %narmafzam_archive_form_front_contract%
            $handler: '@Narmafzam\ArchiveBundle\Model\Handler\ContractHandler'
        tags:
            - name: 'controller.service_arguments'

    # ContractAttachment
    Narmafzam\ArchiveBundle\Form\Common\ContractAttachmentType:
        arguments:
            $dataClass: %narmafzam_archive_entity_contract_attachment%
        tags:
            - {name: form.type}
