narmafzam_archive:
    resource: '@NarmafzamArchiveBundle/Controller'
    type: annotation
    prefix: /

narmafzam_archive_back:
    resource: '@NarmafzamArchiveBundle/Controller/Back'
    type: annotation
    prefix: /back/

narmafzam_archive_front:
    resource: '@NarmafzamArchiveBundle/Controller/Front'
    type: annotation
    prefix: /front/
