imports:
    - { resource: 'menu.yml' }
    - { resource: 'contract.yml' }
    - { resource: 'document.yml' }
    - { resource: 'letter.yml' }

parameters:
    web_dir: '%kernel.project_dir%/web'
    upload_path: '/upload'
    upload_contract_path: '%upload_path%/contract'
    upload_document_path: '%upload_path%/document'
    upload_letter_path: '%upload_path%/letter'

services:
