imports:
    - { resource: 'menu.yml' }
    - { resource: 'contract.yml' }
    - { resource: 'document.yml' }
    - { resource: 'letter.yml' }

parameters:
    web_dir: '%kernel.project_dir%/web'
    upload_path: '/upload'

services:

    Narmafzam\ArchiveBundle\Model\Handler\FileHandler:
        arguments:
            $webDirectory: '%web_dir%'
            $uploadPath: '%upload_path%'

    Narmafzam\ArchiveBundle\EventListener\AttachmentFileEventListener:
        arguments:
            - '@Narmafzam\ArchiveBundle\Model\Handler\FileHandler'

        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }