parameters:
    content_directory: '%kernel.project_dir%/var/uploads'

    # Contract
    narmafzam_archive_entity_contract: Narmafzam\ArchiveBundle\Entity\Contract
    narmafzam_archive_form_back_contract: Narmafzam\ArchiveBundle\Form\Back\ContractType
    narmafzam_archive_form_front_contract: Narmafzam\ArchiveBundle\Form\Front\ContractType

    # ContractAttachment
    narmafzam_archive_entity_contract_attachment: Narmafzam\ArchiveBundle\Entity\ContractAttachment

    # =================================================================

    # Document
    narmafzam_archive_entity_document: Narmafzam\ArchiveBundle\Entity\Document
    narmafzam_archive_form_back_document: Narmafzam\ArchiveBundle\Form\Back\DocumentType
    narmafzam_archive_form_front_document: Narmafzam\ArchiveBundle\Form\Front\DocumentType

    # DocumentAttachment
    narmafzam_archive_entity_document_attachment: Narmafzam\ArchiveBundle\Entity\DocumentAttachment

    # =================================================================

    # Letter
    narmafzam_archive_entity_letter: Narmafzam\ArchiveBundle\Entity\Letter
    narmafzam_archive_form_back_letter: Narmafzam\ArchiveBundle\Form\Back\LetterType
    narmafzam_archive_form_front_letter: Narmafzam\ArchiveBundle\Form\Front\LetterType

    # LetterAttachment
    narmafzam_archive_entity_letter_attachment: Narmafzam\ArchiveBundle\Entity\LetterAttachment

services:

    # Contract
    Narmafzam\ArchiveBundle\Form\Common\ContractType:
        arguments:
            $dataClass: %narmafzam_archive_entity_contract%
        tags:
            - {name: form.type}

    Narmafzam\ArchiveBundle\Controller\Back\ContractController:
        arguments:
            $dataClass: %narmafzam_archive_entity_contract%
            $formTypeClass: %narmafzam_archive_form_back_contract%
        tags:
            - name: 'controller.service_arguments'

    Narmafzam\ArchiveBundle\Controller\Front\ContractController:
        arguments:
            $dataClass: %narmafzam_archive_entity_contract%
            $formTypeClass: %narmafzam_archive_form_front_contract%
        tags:
            - name: 'controller.service_arguments'

    # ContractAttachment
    Narmafzam\ArchiveBundle\Form\Common\ContractAttachmentType:
        arguments:
            $dataClass: %narmafzam_archive_entity_contract_attachment%
        tags:
            - {name: form.type}

    # =================================================================

    # Document
    Narmafzam\ArchiveBundle\Form\Common\DocumentType:
        arguments:
            $dataClass: %narmafzam_archive_entity_document%
        tags:
            - {name: form.type}

    Narmafzam\ArchiveBundle\Controller\Back\DocumentController:
        arguments:
            $dataClass: %narmafzam_archive_entity_document%
            $formTypeClass: %narmafzam_archive_form_back_document%
        tags:
            - name: 'controller.service_arguments'

    Narmafzam\ArchiveBundle\Controller\Front\DocumentController:
        arguments:
            $dataClass: %narmafzam_archive_entity_document%
            $formTypeClass: %narmafzam_archive_form_front_document%
        tags:
            - name: 'controller.service_arguments'

    #DocumentAttachment
    Narmafzam\ArchiveBundle\Form\Common\DocumentAttachmentType:
        arguments:
            $dataClass: %narmafzam_archive_entity_document_attachment%
        tags:
            - {name: form.type}

    # =================================================================

    # Letter
    Narmafzam\ArchiveBundle\Form\Common\LetterType:
        arguments:
            $dataClass: %narmafzam_archive_entity_letter%
        tags:
            - {name: form.type}

    Narmafzam\ArchiveBundle\Controller\Back\LetterController:
        arguments:
            $dataClass: %narmafzam_archive_entity_letter%
            $formTypeClass: %narmafzam_archive_form_back_letter%
        tags:
            - name: 'controller.service_arguments'

    Narmafzam\ArchiveBundle\Controller\Front\LetterController:
        arguments:
            $dataClass: %narmafzam_archive_entity_letter%
            $formTypeClass: %narmafzam_archive_form_front_letter%
        tags:
            - name: 'controller.service_arguments'

    # LetterAttachment
    Narmafzam\ArchiveBundle\Form\Common\LetterAttachmentType:
        arguments:
            $dataClass: %narmafzam_archive_entity_letter_attachment%
        tags:
            - {name: form.type}